### ISSUE TITLE
HOW TO "add environment variables to enable push of the Docker container to the Docker Hub"?

### ISSUE THREAD

**Issue by andrewjohnlowe** [benmarwick/rrtools#77] opened 2019-02-07 17:56 UTC
Hi! Could you provide clarification in the README in section 7 (`rrtools::use_travis()`) on how to "add environment variables to enable push of the Docker container to the Docker Hub"? This isn't clear. Thanks!

**Comment by andrewjohnlowe** [comment] 2019-02-07 18:08
OK, so since I want my GitHub repo to be private until publication, I tried to setup with circleci instead:
```
> rrtools::use_circleci(docker_hub = FALSE)
✔ Creating 'circle.yml' from template.
✔ Adding 'circle.yml' to `.Rbuildignore`.
Next: 
 * Add a circleci shield to your README.Rmd:
[![Circle-CI Build Status](https://circleci.com/gh/andrewjohnlowe/qvgjets.svg?style=shield&circle-token=:circle-token)](https://circleci.com/gh/andrewjohnlowe/qvgjets)
 * Turn on circleci for your repo at https://circleci.com/gh//andrewjohnlowe
   and add your environment variables: DOCKER_EMAIL, 
   DOCKER_USER, DOCKER_PASS.
 * Your Docker container will be kept private and NOT be pushed to the Docker Hub
```

* The double slash in https://circleci.com/gh//andrewjohnlowe is a typo that causes the URL to 404.
* I don't know how to add the environment variables here either.

**Comment by andrewjohnlowe** [comment] 2019-02-08 11:08
Thanks, but I'm still confused. I don't know what those values are. I want to execute my RMarkdown using Binder, just as Carl Boettiger has done here: https://github.com/cboettig/noise-phenomena

I'd like to add that I believe most of us in my field -- including myself -- are not familiar with Docker and other tools that would be useful for reproducible research, which may be why I haven't seen a single example of a research compendium in my field. Lack of technical knowledge is a huge impediment; surely my colleagues would be doing it if it were easier to get started. Your package could go a long way to solving that -- thanks! I'm hoping that my paper can serve as a roadmap for my colleagues, but I don't understand the whole process myself yet, so I'm nowhere near having a step-by-step guide yet.

**Comment by andrewjohnlowe** [comment] 2019-02-08 23:23
I don't actually need these values if I'm using circleci, right? This is just for pushing to docker hub, which I definitely don't want to do until after publication. So I probably don't want to use travis right now. I'll try again on Monday.

**Comment by benmarwick** [comment] 2019-02-08 23:23
If you want to execute your Rmd in Binder, that is different from your original question about environment variables on Travis and Circle at the start of this thread. The environment variables that you originally asked about are a way to give Travis and Circle your secret details (e.g. username and password) so Travis and Circle can use them to log in on your behalf and do things for you (like update the docker hub with you most current docker container, or update your GitHub repository). 

By the way, next time could you please start a new issue for a different question? That's more helpful for other people who have similar questions, and makes it easier for us to help you better by minimizing confusion. 

All of these things, travis, circle, binder, docker, etc. are very new in most research communities, so most people are seeing them here for the first time. It's highly likely you will one of first people to use these tools in your field because they are so new.  It's an exciting time!

We assume that if you are using the Travis or Circle-CI services, then you have already familiarised yourself about them by reading the papers in [our reference list](https://github.com/benmarwick/rrtools#references). Have you read those? They are short, clear and concise on how these services fit in making research reproducible. That will help you to understand how those parts fit it, and whether or not they make sense for your research.

About your new question on using Binder with your Rmd:

If you want to use Binder as @cboettig has done, you need to:
- Have your compendium at a public GitHub repository (it wont work on private repos)
- Have a DESCRIPTION file in this public GitHub repository (or see @karthik's excellent notes on many other ways [here](https://github.com/karthik/rstudio2019/blob/master/binder-notes.md), this is the best resource for information on Binder and R at the moment)
- edit your README.Rmd to include a line like this: 

```
[![Binder](http://mybinder.org/badge.svg)](http://beta.mybinder.org/v2/gh/yourusername/yourreponame/master?urlpath=rstudio)
```

And change yourusername/yourreponame to your actual names. You can see a working example in the raw markdown of Carl's repo that you mention: https://raw.githubusercontent.com/cboettig/noise-phenomena/master/README.md

That will add the Binder button to your README on GitHub. You click on the button, and that starts Binder in a new tab. No further configuration required. 

I'll close this thread now, but please don't hesitate to ask questions about rrtools or the related services by starting a new discussion (and after you've done the required reading 😉  )

**Closed by benmarwick** 2019-02-08 23:23 UTC

**Comment by andrewjohnlowe** [comment] 2019-02-08 23:39
Thanks for the clarification! That's very helpful. Sorry for the newbie questions. I'm working my way through the papers. Never used CI tools before, so this concept is unfamiliar to me and still a bit confusing. I'll look for a dummies guide to CI, travis, circle. Cheers!
